### ISSUE TITLE
SyntaxError at first start

### ISSUE THREAD

**Issue by Aeris1One** [ClemsonCPSC-Discord/ClemBot#302]
Just followed the CONTRIBUTING.md to install a dev env, only thing I changed was the `virtualenv venv` command changed to `virtualenv venv --python=python3` to avoid using python2 which is default of virtualenv.

```
2021-04-03 08:59:10,020 INFO Attempting to load BotSecrets.json from /home/admin/ClemBot
2021-04-03 08:59:10,021 INFO Bot Secrets Loaded
2021-04-03 08:59:10,021 INFO New messenger created with name: primary_bot_messenger
2021-04-03 08:59:10,021 INFO Setting default prefix too: "!""
2021-04-03 08:59:10,021 INFO Registering new event: on_set_custom_prefix to Messenger: primary_bot_messenger
2021-04-03 08:59:10,021 INFO Registering listener <bound method CustomPrefix.set_prefix of <bot.custom_prefix.CustomPrefix object at 0x7f8d3e55abe0>> to event: on_set_custom_prefix in Messenger: primary_bot_messenger
2021-04-03 08:59:10,022 INFO Bot Starting Up
2021-04-03 08:59:10,052 WARNING PyNaCl is not installed, voice will NOT be supported
2021-04-03 08:59:10,052 INFO Loading Cogs
2021-04-03 08:59:10,071 INFO Loading cog: bot.cogs.assignable_roles_cog
2021-04-03 08:59:10,088 INFO Loading cog: bot.cogs.base_converter.base_converter_cog
2021-04-03 08:59:10,106 INFO Loading cog: bot.cogs.calculator_cog
2021-04-03 08:59:10,121 INFO Loading cog: bot.cogs.claims_authorization_cog
2021-04-03 08:59:10,129 INFO Loading cog: bot.cogs.custom_prefix_cog
2021-04-03 08:59:10,135 INFO Loading cog: bot.cogs.define_cog
2021-04-03 08:59:10,142 INFO Loading cog: bot.cogs.designated_channels_cog
2021-04-03 08:59:10,148 INFO Loading cog: bot.cogs.emote_cog
2021-04-03 08:59:10,156 INFO Loading cog: bot.cogs.eval_cog
2021-04-03 08:59:10,161 INFO Loading cog: bot.cogs.example_cog
2021-04-03 08:59:10,167 INFO Loading cog: bot.cogs.gif_me_cog
2021-04-03 08:59:10,178 INFO Loading cog: bot.cogs.grades_data.grades_cog
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/admin/ClemBot/bot/__main__.py", line 102, in <module>
    main()
  File "/home/admin/ClemBot/bot/__main__.py", line 97, in main
    intents=intents
  File "/home/admin/ClemBot/bot/clem_bot.py", line 42, in __init__
    self.load_cogs()
  File "/home/admin/ClemBot/bot/clem_bot.py", line 288, in load_cogs
    for m in ClemBot.walk_modules('cogs', cogs): 
  File "/home/admin/ClemBot/bot/clem_bot.py", line 301, in walk_modules
    yield importlib.import_module(name)
  File "/home/admin/ClemBot/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/admin/ClemBot/bot/cogs/help_cog.py", line 90
    if result := self.find_command(c, command_name):
               ^
SyntaxError: invalid syntax
```

**Comment by kspalm** [comment]
`:=` is the walrus operator and is new in Python 3.8, which is what we use for all of ClemBot. Looks like you're using 3.7!

**Comment by Aeris1One** [comment]
Yes, python3.7, i'll upgrade to 3.8. Thanks ^^

**Comment by Jay-Madden** [comment]
Thank you for bringing this up, i just added that requirement to contributing.md f98ff956b8e3221d4eeb0705950d381421e4e4b0
